#openai_api_key=""
#limewire_api_key="lmwr_sk_ubVsrmnSsK_bdyvN9XG9v1btyykYQrnfOAjDkWKN2PrcKQ3k"
google_gemini_api_key="AIzaSyAViZZVNOTDl_MsLDPDbEZS6R1Ppv47e8I"
UNSPLASH_ACCESS_KEY="qHqLXNdO_MUi16tNwNYwpbGcDFAK4u4nP687Ewps62Y"